name: DevOps Check Sheet Analysis
permissions:
  contents: read
  issues: read
on:
  schedule:
    - cron: '0 0 * * 1'  # Runs every week on Monday
  workflow_dispatch:  # Allow manual triggering
  issues:
    types: [closed]  # Run when issues are closed
  push:
    branches:
      - master
jobs:
  generate-check-sheet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests matplotlib seaborn pandas numpy

      - name: Run check sheet generator
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          python .github/scripts/checksheet.py

      - name: Upload diagram as artifact
        uses: actions/upload-artifact@v4
        with:
          name: devops-checksheet
          path: checksheet_*.png
          retention-days: 90  # Keep artifacts for 90 days
