name: Cause and Effect Analysis

permissions:
  contents: write
  issues: read

on:
  schedule:
    - cron: '0 0 1 * *'  # S'executa el primer dia de cada mes
  workflow_dispatch:  # Permet execució manual
  issues:
    types: [closed]  # Executa quan es tanquen issues
  push:
    branches:
      - main

jobs:
  generate-check-sheet:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests matplotlib pandas
      
      - name: Run check sheet generator
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          python .github/scripts/checksheet.py
      
      - name: Debug output folder
        run: ls -l output/

      - name: Verify generated files
        run: |
          if [ -f "checksheet_data.json" ]; then echo "✅ JSON generat correctament"; else echo "❌ JSON no trobat"; fi
          if [ -f "output/checksheet_table.png" ]; then echo "✅ Imatge generada correctament"; else echo "❌ Imatge no trobada"; fi
      
      - name: Upload Checksheet as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: checksheet-files
          path: |
            checksheet_data.json
            output/checksheet_table.png
