name: Weekly Issues Run Chart

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

permissions:
  contents: write  # 游눤 Esto da permiso al token para hacer push

jobs:
  generate-weekly-chart:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout c칩digo
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install matplotlib numpy requests

      - name: Ejecutar script y generar gr치fico
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python .github/workflows/try_issues.py

      - name: Commit y push gr치fico
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add grafico_issues_semanal.pdf
          git commit -m "Gr치fico semanal de issues actualizado"
          git push
